<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyVersion>25.11.11</AssemblyVersion>
    <FileVersion>25.11.11</FileVersion>
    <CopyLocalLockFileAssemblies>True</CopyLocalLockFileAssemblies>
    <IncludeSourceRevisionInInformationalVersion>true</IncludeSourceRevisionInInformationalVersion>
    <AssemblyName>PinyinSeek</AssemblyName>
    <RootNamespace>PinyinSeek</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- 核心 Emby 依赖 -->
    <PackageReference Include="mediabrowser.server.core" Version="4.9.1.80" />
    <!-- 使用 TinyPinyin -->
    <PackageReference Include="TinyPinyin" Version="1.1.0" />
    <!-- 添加 ILRepack -->
    <PackageReference Include="ILRepack" Version="2.0.44">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="PinyinSeekLogo.png" />
  </ItemGroup>

  <Target Name="ILRepack" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <Exec Command="$(ILRepack) /out:&quot;$(OutputPath)$(TargetFileName)&quot; &quot;$(TargetPath)&quot; $(TargetDir)TinyPinyin.dll /lib:&quot;$(TargetDir)&quot;" />
  </Target>

</Project>
