name: Build Emby Plugin

on:
  push:
    branches: [ "main" ] # 或者你希望触发编译的分支
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x # 确保与项目文件中的 TargetFramework 匹配
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: EmbyPinyinPlugin-${{ github.sha }} # 生成的文件名包含提交 SHA
        path: |
          **/bin/Release/net8.0/EmbyPinyinPlugin.dll # 根据你的 AssemblyName 和 TargetFramework 调整
